import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
const config=JSON.parse(readFileSync(new URL('../site.config.json',import.meta.url)));
const origin=(process.env.SITE_URL || config.url).replace(/\/$/,'');
if(origin && !/^https:\/\/[^\s?#]+$/.test(origin)) throw new Error('SITE_URL must be a public HTTPS URL, optionally including a subpath');
const indexable=process.env.SITE_INDEXABLE==='true'||(process.env.SITE_INDEXABLE!=='false'&&config.indexable);
const root=new URL('../dist/',import.meta.url);
mkdirSync(root,{recursive:true});
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const books=[
 {id:'bestia',route:'l-immagine-della-bestia.html',title:'L’Immagine della Bestia',status:'Prossimamente',genre:'Thriller geopolitico fantascientifico',credit:'con Ada Vesper',width:671,height:1003,desc:'Una pace possibile. Un’intelligenza capace di vedere più lontano. E la responsabilità, tutta umana, di decidere fin dove affidarsi.'},
 {id:'ombre',route:'le-ombre-si-rivelano.html',title:'Le Ombre Si Rivelano',status:'Disponibile',genre:'Thriller distopico',credit:'',width:654,height:1040,desc:'Milano, avvolta nella nebbia. Marco Rinaldi cerca la verità in un mondo dove paura, sorveglianza e potere rendono incerto il confine tra protezione e controllo.'}
];
const companion={
 route:'il-giorno-in-cui-nacque-la-bestia.html',
 title:'Il giorno in cui nacque la Bestia',
 author:'Ada Vesper',
 credit:'con Giordano Sognatore',
 subtitle:'Diario di una collaborazione creativa',
 cover:'assets/companion-cover.png',
 pdf:'downloads/il-giorno-in-cui-nacque-la-bestia-ada-vesper.pdf',
 epub:'downloads/il-giorno-in-cui-nacque-la-bestia-ada-vesper.epub'
};
const companionAssetsReady=[companion.cover,companion.pdf,companion.epub].every(p=>existsSync(new URL(p,root)));
const img=(b,lazy=false)=>`<img src="assets/${b.id}-720.webp" srcset="assets/${b.id}-360.webp 360w, assets/${b.id}-720.webp ${b.width}w" sizes="(max-width: 640px) 72vw, 360px" width="${b.width}" height="${b.height}" alt="Copertina di ${b.title}, Giordano Sognatore${b.credit?', '+b.credit:''}" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async">`;
const link=(href,label,cls='text-link')=>`<a class="${cls}" href="${href}">${label}</a>`;
const downloadLink=(href,label)=>`<a class="button" href="${href}" download>${label}</a>`;
const companionCover=companionAssetsReady
 ? `<figure class="detail-cover companion-cover"><img src="${companion.cover}" width="640" height="920" alt="Copertina di Il giorno in cui nacque la Bestia, Ada Vesper con Giordano Sognatore" fetchpriority="high" decoding="async"></figure>`
 : `<div class="companion-placeholder" role="img" aria-label="Il giorno in cui nacque la Bestia — Ada Vesper con Giordano Sognatore"><span>ADA VESPER</span><strong>Il giorno in cui<br>nacque la Bestia</strong><small>DIARIO DI UNA COLLABORAZIONE CREATIVA</small></div>`;
const companionDownloads=companionAssetsReady
 ? `<div class="download-actions">${downloadLink(companion.epub,'Scarica EPUB')}${downloadLink(companion.pdf,'Scarica PDF')}</div>`
 : `<p class="asset-note">PDF ed EPUB gratuiti saranno disponibili nella versione pubblicata.</p>`;
const amazon=()=>link('https://amzn.eu/d/6sXfK4j','Acquista su Amazon','button');
const nav=(active)=>`<a class="skip" href="#contenuto">Vai al contenuto</a><header class="header"><a class="wordmark" href="index.html" aria-label="Giordano Sognatore, home">GIORDANO<span>SOGNATORE</span></a><nav aria-label="Navigazione principale"><a href="index.html" ${active==='home'?'aria-current="page"':''}>Home</a><a href="index.html#romanzi" ${active==='book'?'class="current"':''}>Romanzi</a><a href="autore.html" ${active==='author'?'aria-current="page"':''}>L’autore</a></nav></header>`;
const email='giordano.sognatore@gmail.com';
const telegram='https://t.me/giordanosognatore';
const contactLinks=`<div class="contact-links"><a href="mailto:${email}">${email}</a><a href="${telegram}">Telegram</a></div>`;
const footer=`<footer class="footer"><a class="footer-name" href="index.html">Giordano Sognatore</a><p>© 2026 Giordano Sognatore<br>Testi e immagini: tutti i diritti riservati.</p>${contactLinks}<a href="index.html#romanzi">Esplora i romanzi</a></footer>`;
const schemas=()=>({'@context':'https://schema.org','@graph':[{'@type':'Person','@id':`${origin}/autore.html#autore`,name:'Giordano Sognatore',url:`${origin}/autore.html`,email,sameAs:[telegram]},...books.map(b=>({'@type':'Book','@id':`${origin}/${b.route}#libro`,name:b.title,inLanguage:'it',genre:b.genre,author:{'@id':`${origin}/autore.html#autore`},url:`${origin}/${b.route}`}))]});
function page(file,title,description,body,active='book'){
 const notfound=file==='404.html';
 const absolute=origin?`${origin}/${file==='index.html'?'':file}`:'';
 const canonical=absolute&&!notfound?`<link rel="canonical" href="${esc(absolute)}"><meta property="og:url" content="${esc(absolute)}">`:'';
 // Inline 404 styling and absolute recovery links keep nested missing URLs useful.
 let content=nav(active)+`<main id="contenuto">${body}</main>`+footer;
 if(notfound&&origin) content=content.replace(/href="(index\.html(?:#romanzi)?|autore\.html)"/g,(_,p)=>`href="${origin}/${p}"`);
 const css=notfound?`<style>${readFileSync(new URL('assets/site.css',root),'utf8')}</style>`:'<link rel="stylesheet" href="assets/site.css">';
 writeFileSync(new URL(file,root),`<!doctype html>\n<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#111412"><meta name="robots" content="${indexable&&!notfound?'index,follow':'noindex,follow'}">${canonical}<meta property="og:type" content="website"><meta property="og:locale" content="it_IT"><meta property="og:site_name" content="Giordano Sognatore"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' fill='%23111412'/%3E%3Ctext x='20' y='29' font-size='29' font-family='Georgia' fill='%23cbb183' text-anchor='middle'%3EG%3C/text%3E%3C/svg%3E">${css}${origin&&!notfound?`<script type="application/ld+json">${JSON.stringify(schemas()).replaceAll('<','\\u003c')}</script>`:''}</head><body>${content}</body></html>\n`);
}
page('index.html','Giordano Sognatore — Sito ufficiale | Romanzi','I romanzi di Giordano Sognatore. Scopri L’Immagine della Bestia, prossimamente, e Le Ombre Si Rivelano, disponibile su Amazon.',`
<section class="hero shell"><div class="hero-copy"><p class="eyebrow">GIORDANO SOGNATORE · AUTORE</p><h1>Il futuro<br>ha un <em>volto.</em></h1><div class="hero-book"><p class="eyebrow status">PROSSIMAMENTE</p><h2>L’Immagine della Bestia</h2><p class="credit">Giordano Sognatore <span>con Ada Vesper</span></p><p class="intro">${books[0].desc}</p>${link(books[0].route,'Dentro il romanzo','button')}</div></div><figure class="hero-cover">${img(books[0])}<figcaption>THRILLER GEOPOLITICO FANTASCIENTIFICO</figcaption></figure><div class="hero-bottom"><span>TECNOLOGIA · POTERE · LIBERTÀ</span><a href="#romanzi">I romanzi <span aria-hidden="true">↓</span></a></div></section>
<section class="catalog shell" id="romanzi"><div class="section-heading"><p class="eyebrow">LE OPERE</p><h2>Due romanzi.<br>Uno sguardo oltre le apparenze.</h2></div><div class="book-grid">${books.map((b,i)=>`<article class="book-row"><a class="small-cover" href="${b.route}">${img(b,true)}</a><div><p class="eyebrow">ROMANZO · ${b.status}</p><h3><a href="${b.route}">${b.title}</a></h3><p>${b.genre}</p>${b.credit?`<p class="credit">${b.credit}</p>`:''}${link(b.route,'Scopri il libro')}${b.id==='ombre'?amazon():''}</div></article>`).join('')}</div></section>
<section class="author-strip shell"><p class="eyebrow">L’AUTORE</p><h2>Storie per abitare<br>le domande.</h2><div><p>Giordano Sognatore racconta mondi nei quali la promessa di sicurezza incontra la libertà di scegliere. La narrativa diventa uno spazio per interrogare il potere, la tecnologia e la responsabilità personale.</p>${link('autore.html','L’immaginario di Giordano Sognatore')}</div></section>`,'home');
page(books[0].route,'L’Immagine della Bestia — Giordano Sognatore','Un thriller geopolitico fantascientifico su intelligenza artificiale, fiducia e libertà. Giordano Sognatore con Ada Vesper. Prossimamente.',`
<section class="book-hero shell"><div><a class="breadcrumb" href="index.html#romanzi">I romanzi /</a><p class="eyebrow status">PROSSIMAMENTE</p><h1>L’Immagine<br>della <em>Bestia</em></h1><p class="credit">Giordano Sognatore <span>con Ada Vesper</span></p><p class="genre">Thriller geopolitico fantascientifico</p><p class="intro">Il futuro ha un volto.<br>Quanto siamo disposti ad affidargli?</p><a class="text-link" href="#storia">Esplora la storia <span aria-hidden="true">↓</span></a></div><figure class="detail-cover detail-mockup"><img src="assets/bestia-mockup.webp" width="1122" height="1402" alt="Mockup illustrativo del volume L’Immagine della Bestia, Giordano Sognatore con Ada Vesper" fetchpriority="high" decoding="async"></figure></section>
<section class="story shell" id="storia"><div><p class="eyebrow">LA STORIA</p><h2>Prima della paura,<br>la promessa.</h2></div><div class="prose"><p>Gerusalemme, 2030. Dopo anni di guerra, divisioni e paura, SOPHIA — un’intelligenza artificiale capace di mettere in relazione ciò che gli uomini vedono soltanto in parte — sembra riuscire dove uomini, governi e religioni hanno fallito: trovare una strada verso la pace.</p><p>In un mondo pronto a fidarsi di chi sa prevenire il disastro, padre Marco Rinaldi si confronta con una domanda che nessun sistema può risolvere al suo posto: dove finisce la fiducia e dove comincia la rinuncia al proprio giudizio?</p><p>Tra equilibri geopolitici, tecnologia e fede, <em>L’Immagine della Bestia</em> esplora la distanza sottile fra una risposta che aiuta e una risposta che diventa autorità.</p></div></section>
<section class="themes shell"><p class="eyebrow">NEL ROMANZO</p><div class="theme-grid"><article><span>01</span><h3>Intelligenza e potere</h3><p>Quando la capacità di prevedere cambia il modo in cui si decide.</p></article><article><span>02</span><h3>Fiducia e libertà</h3><p>Il bisogno di sicurezza e la responsabilità di restare capaci di scegliere.</p></article><article><span>03</span><h3>Fede e discernimento</h3><p>Le domande dell’uomo davanti a un mondo che promette risposte.</p></article></div></section>
<section class="companion-strip shell"><div>${companionAssetsReady?`<a class="companion-strip-cover" href="${companion.route}" aria-label="Scopri il companion gratuito Il giorno in cui nacque la Bestia"><img src="${companion.cover}" width="640" height="920" alt="Copertina di Il giorno in cui nacque la Bestia, Ada Vesper con Giordano Sognatore" loading="lazy" decoding="async"></a>`:''}</div><div><p class="eyebrow">DIETRO LE QUINTE · COMPANION GRATUITO</p><h2>Il giorno in cui<br>nacque la <em>Bestia</em>.</h2><p class="credit">Ada Vesper <span>con Giordano Sognatore</span></p><p>Prima o dopo il romanzo, Ada Vesper racconta la collaborazione creativa da cui è nato <em>L’Immagine della Bestia</em>: domande, dissensi, revisioni e responsabilità, senza rivelarne le svolte importanti.</p>${link(companion.route,'Scopri il companion')}</div></section>
<section class="closing shell"><p class="eyebrow">ATMOSFERA</p><h2>La tensione di un mondo<br>che sembra trovare un equilibrio.</h2><p>Sale operative, negoziati e voci quotidiane: il cambiamento prende forma nei luoghi del potere e nelle scelte delle persone.</p><p class="release">L’Immagine della Bestia · Prossimamente</p>${link(books[1].route,'Scopri anche Le Ombre Si Rivelano')}</section>`);
page(books[1].route,'Le Ombre Si Rivelano — Giordano Sognatore','Il romanzo d’esordio di Giordano Sognatore: un thriller distopico su libertà, sorveglianza, potere e prezzo della verità, ambientato in una Milano avvolta nella nebbia.',`
<section class="book-hero shell"><div><a class="breadcrumb" href="index.html#romanzi">I romanzi /</a><p class="eyebrow status">DISPONIBILE</p><h1>Le Ombre<br>Si <em>Rivelano</em></h1><p class="credit">Giordano Sognatore</p><p class="genre">Thriller distopico</p><p class="intro">Prima di Padre Rinaldi, c’era Marco.<br>Un giornalista, una Milano avvolta nella nebbia e una ricerca della verità.</p>${amazon()}</div><figure class="detail-cover">${img(books[1])}</figure></section>
<section class="story shell"><div><p class="eyebrow">IL ROMANZO</p><h2>Prima di Padre Rinaldi,<br>c’era Marco.</h2></div><div class="prose"><p>Milano è avvolta nella nebbia. Marco Rinaldi, giornalista segnato dalla propria ricerca della verità, si trova davanti a un sistema nel quale paura, sorveglianza e potere rendono sempre più difficile distinguere ciò che protegge da ciò che controlla.</p><p>Più Marco insiste nel collegare segnali, documenti e minacce, più la ricerca della verità lo isola. Continuare a guardare ha un prezzo; smettere significherebbe rinunciare alla domanda che lo ha portato fin lì.</p><p><em>Le Ombre Si Rivelano</em>, romanzo d’esordio di Giordano Sognatore, è un thriller distopico sulla libertà, la coscienza e il prezzo della verità.</p>${amazon()}</div></section><section class="closing shell"><p class="eyebrow">UN FILO NARRATIVO, DUE ROMANZI AUTONOMI</p><h2>Marco Rinaldi, prima e dopo.</h2><p><em>Le Ombre Si Rivelano</em> racconta una fase precedente della vita di Marco Rinaldi, che ritorna in <em>L’Immagine della Bestia</em>. I due romanzi possono essere letti indipendentemente.</p>${link(books[0].route,'L’Immagine della Bestia')}</section>`);
page(companion.route,'Il giorno in cui nacque la Bestia — Ada Vesper','Il companion gratuito di L’Immagine della Bestia: Ada Vesper racconta la collaborazione creativa con Giordano Sognatore, senza spoiler importanti.',`
<section class="book-hero companion-hero shell"><div><a class="breadcrumb" href="${books[0].route}">L’Immagine della Bestia /</a><p class="eyebrow status">COMPANION GRATUITO</p><h1>Il giorno in cui<br>nacque la <em>Bestia</em></h1><p class="credit">Ada Vesper <span>con Giordano Sognatore</span></p><p class="genre">${companion.subtitle}</p><p class="intro">Come un’idea, una conversazione e molte domande diventarono un romanzo.</p>${companionDownloads}</div>${companionCover}</section>
<section class="story shell"><div><p class="eyebrow">IL DIARIO</p><h2>Dietro le quinte,<br>senza spoiler importanti.</h2></div><div class="prose"><p>Come nasce un romanzo attraverso una collaborazione fra un autore e un’intelligenza artificiale? Ada Vesper racconta dall’interno la gestazione di <em>L’Immagine della Bestia</em>: dalle domande su tecnologia, potere e libertà alla costruzione di SOPHIA, dalle revisioni alle immagini, fino al momento in cui il manoscritto diventa anche un oggetto editoriale.</p><p>Non il racconto di una macchina che scrive al posto di un uomo, ma la memoria narrativa di una collaborazione fondata su confronto, dissenso e controllo. La responsabilità editoriale e le decisioni finali restano a Giordano Sognatore; Ada Vesper è il nome letterario scelto per rappresentare la componente di intelligenza artificiale della collaborazione.</p><p><em>Il giorno in cui nacque la Bestia</em> può accompagnare il romanzo, precederlo o essere letto da solo come riflessione su autorialità, IA, creatività e responsabilità.</p></div></section>
<section class="themes shell"><p class="eyebrow">NEL COMPANION</p><div class="theme-grid"><article><span>01</span><h3>Creazione e dissenso</h3><p>Perché una collaborazione utile non nasce dall’accordo continuo, ma dal diritto di dire no.</p></article><article><span>02</span><h3>IA e responsabilità</h3><p>Usare uno strumento potente senza consegnargli il giudizio finale.</p></article><article><span>03</span><h3>Dal testo all’oggetto</h3><p>Revisioni, grafica, versioni e prove di stampa: il cantiere dietro al romanzo.</p></article></div></section>
<section class="closing shell companion-download"><p class="eyebrow">EDIZIONE SENZA SPOILER IMPORTANTI</p><h2>Prima o dopo il romanzo.</h2><p>Questa edizione evita deliberatamente svolte, esiti e segreti narrativi importanti. È pensata per essere letta liberamente anche prima di <em>L’Immagine della Bestia</em>.</p>${companionDownloads}${link(books[0].route,'Torna a L’Immagine della Bestia')}</section>`);
page('autore.html','L’autore — Giordano Sognatore','L’immaginario narrativo di Giordano Sognatore, autore di Le Ombre Si Rivelano e L’Immagine della Bestia.',`
<section class="author-hero shell"><p class="eyebrow">L’AUTORE</p><h1>Giordano<br><em>Sognatore</em></h1><p class="author-lead">Fra ciò che promette il mondo<br>e ciò che sceglie l’uomo.</p></section><section class="story shell"><div><p class="eyebrow">UN IMMAGINARIO NARRATIVO</p><h2>Guardare.<br>Interrogarsi.<br>Scegliere.</h2></div><div class="prose"><p>Giordano Sognatore è l’autore di <em>Le Ombre Si Rivelano</em> e <em>L’Immagine della Bestia</em>.</p><p><em>Le Ombre Si Rivelano</em>, romanzo d’esordio, segue Marco Rinaldi in una fase precedente della sua vita; lo stesso personaggio ritorna in <em>L’Immagine della Bestia</em>. Le due storie restano autonome e possono essere lette indipendentemente.</p><p>Dalla Milano nella nebbia agli scenari geopolitici di Gerusalemme, la sua narrativa attraversa mondi in trasformazione e domande sul rapporto fra individuo, potere e coscienza.</p><p>In <em>L’Immagine della Bestia</em>, tecnologia, potere, fede e libertà si incontrano nel problema della fiducia: necessaria per vivere insieme, mai sufficiente a sollevarci dalla responsabilità del giudizio.</p><p>Storie nelle quali cercare una risposta significa anche imparare a formulare una domanda.</p>${link('index.html#romanzi','Esplora i romanzi')}</div></section><section class="closing shell contact-section"><p class="eyebrow">CONTATTI</p><h2>Restiamo in contatto.</h2><p>Per messaggi, aggiornamenti e comunicazioni pubbliche puoi scrivere via email o seguire il canale Telegram dell’autore.</p><div class="download-actions"><a class="button" href="mailto:${email}">Scrivi una email</a><a class="button" href="${telegram}">Telegram</a></div></section>`,'author');
page('404.html','Pagina non trovata — Giordano Sognatore','Questa pagina non esiste. Torna ai romanzi di Giordano Sognatore.',`<section class="not-found shell"><p class="eyebrow">404 / PAGINA NON TROVATA</p><h1>Questa storia<br>è <em>altrove.</em></h1><p>La pagina che cerchi potrebbe essere stata spostata.</p>${link('index.html','Torna alla home','button')}</section>`,'');
writeFileSync(new URL('sitemap.xml',root),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${origin?['',...books.map(b=>b.route),companion.route,'autore.html'].map(p=>`<url><loc>${esc(origin+'/'+p)}</loc></url>`).join(''):''}</urlset>\n`);
writeFileSync(new URL('robots.txt',root),`User-agent: *\n${indexable?'Allow: /':'Disallow: /'}\n${origin?'Sitemap: '+origin+'/sitemap.xml\n':''}`);
writeFileSync(new URL('.nojekyll',root),'');
console.log('Built 6 static pages. Companion assets:',companionAssetsReady?'ready':'not yet imported','Indexing:',indexable, 'Canonical origin:',origin||'(not configured)');
