import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {nav} from './navigation.mjs';

const config=JSON.parse(readFileSync(new URL('../site.config.json',import.meta.url)));
const origin=(process.env.SITE_URL || config.url).replace(/\/$/,'');
const indexable=process.env.SITE_INDEXABLE==='true'||(process.env.SITE_INDEXABLE!=='false'&&config.indexable);
const root=resolve(new URL('../dist/',import.meta.url).pathname);
const email='giordano.sognatore@gmail.com';
const telegram='https://t.me/giordanosognatore';
const amazon='https://amzn.eu/d/023g6Qe1';
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');

const schema=()=>({'@context':'https://schema.org','@graph':[
 {'@type':'Person','@id':`${origin}/autore.html#autore`,name:'Giordano Sognatore',url:`${origin}/autore.html`,email,sameAs:[telegram]},
 {'@type':'Book','@id':`${origin}/l-immagine-della-bestia.html#libro`,name:'L’Immagine della Bestia',inLanguage:'it',genre:'Thriller geopolitico fantascientifico',author:{'@id':`${origin}/autore.html#autore`},url:`${origin}/l-immagine-della-bestia.html`},
 {'@type':'Book','@id':`${origin}/le-ombre-si-rivelano.html#libro`,name:'Le Ombre Si Rivelano',inLanguage:'it',genre:'Thriller distopico',author:{'@id':`${origin}/autore.html#autore`},url:`${origin}/le-ombre-si-rivelano.html`}
]});

const contactLinks=`<div class="contact-links"><a href="mailto:${email}" aria-label="Email: ${email}">Email</a><a href="${telegram}">Telegram</a></div>`;
const footer=`<footer class="footer"><a class="footer-name" href="index.html">Giordano Sognatore</a><p>© 2026 Giordano Sognatore<br>Testi e immagini: tutti i diritti riservati.</p>${contactLinks}<a href="press.html">Press & media</a></footer>`;
const link=(href,label,cls='text-link')=>`<a class="${cls}" href="${href}">${label}</a>`;

function page(file,title,description,body,active='press'){
 const absolute=origin?`${origin}/${file}`:'';
 const canonical=absolute?`<link rel="canonical" href="${esc(absolute)}"><meta property="og:url" content="${esc(absolute)}">`:'';
 writeFileSync(resolve(root,file),`<!doctype html>\n<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#111412"><meta name="robots" content="${indexable?'index,follow':'noindex,follow'}">${canonical}<meta property="og:type" content="website"><meta property="og:locale" content="it_IT"><meta property="og:site_name" content="Giordano Sognatore"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' fill='%23111412'/%3E%3Ctext x='20' y='29' font-size='29' font-family='Georgia' fill='%23cbb183' text-anchor='middle'%3EG%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="assets/site.css">${origin?`<script type="application/ld+json">${JSON.stringify(schema()).replaceAll('<','\\u003c')}</script>`:''}<script src="assets/navigation.js" defer></script></head><body>${nav(active)}<main id="contenuto">${body}</main>${footer}</body></html>\n`);
}

for(const file of readdirSync(root).filter(name=>name.endsWith('.html'))){
 const path=resolve(root,file);
 const html=readFileSync(path,'utf8').replaceAll('https://amzn.eu/d/0gZG6TFN',amazon);
 writeFileSync(path,html);
}

page('press.html','Press & media — Giordano Sognatore','Materiali per stampa, podcast, recensioni e interviste su Giordano Sognatore e L’Immagine della Bestia.',`
<section class="author-hero shell"><p class="eyebrow">PRESS & MEDIA</p><h1>Una storia.<br><em>Molte domande.</em></h1><p class="author-lead">Materiali essenziali per stampa, podcast, recensioni e incontri.</p></section>
<section class="story shell"><div><p class="eyebrow">L’IMMAGINE DELLA BESTIA</p><h2>Scheda rapida.</h2></div><div class="prose"><p><strong>Titolo:</strong> <em>L’Immagine della Bestia</em><br><strong>Autore:</strong> Giordano Sognatore<br><strong>Credito:</strong> con Ada Vesper<br><strong>Genere:</strong> thriller geopolitico fantascientifico<br><strong>Ambientazione:</strong> Gerusalemme, 2030<br><strong>Temi:</strong> intelligenza artificiale, potere, libertà, fede, responsabilità, pace.</p><p>Un’intelligenza artificiale nata per aiutare un mondo stanco di guerre conquista progressivamente fiducia e autorità. Marco Rinaldi osserva la promessa di pace con una domanda sempre più difficile da ignorare: quando uno strumento funziona davvero, fino a che punto siamo disposti ad affidargli il nostro giudizio?</p><div class="download-actions"><a class="button" href="${amazon}">Amazon</a><a class="button" href="mailto:${email}?subject=Richiesta%20review%20copy%20-%20L%27Immagine%20della%20Bestia">Richiedi review copy</a></div></div></section>
<section class="story shell"><div><p class="eyebrow">BIO</p><h2>Giordano Sognatore.</h2></div><div class="prose"><p><strong>Bio breve.</strong> Giordano Sognatore è autore di narrativa distopica e speculativa. Nei suoi romanzi intreccia tecnologia, libertà, potere, fede e responsabilità personale. <em>L’Immagine della Bestia</em>, scritto con l’ausilio dell’intelligenza artificiale nel processo creativo ed editoriale, è il suo progetto narrativo più ampio.</p><p><strong>Bio media.</strong> Giordano Sognatore scrive storie in cui le grandi trasformazioni tecnologiche e politiche diventano domande personali. Dopo il romanzo d’esordio <em>Le Ombre Si Rivelano</em>, più istintivo e acerbo, ha sviluppato <em>L’Immagine della Bestia</em>, thriller geopolitico fantascientifico ambientato in un futuro molto vicino. Pubblica sotto pseudonimo e preferisce mantenere la propria immagine privata; è disponibile per interviste scritte e collegamenti audio.</p></div></section>
<section class="themes shell"><p class="eyebrow">PER UN’INTERVISTA</p><div class="theme-grid"><article><span>01</span><h3>IA e autorialità</h3><p>Che cosa significa scrivere un romanzo con l’IA come collaboratrice creativa senza delegarle la responsabilità finale?</p></article><article><span>02</span><h3>Potere e fiducia</h3><p>Quando la capacità di prevedere e consigliare rischia di trasformarsi in autorità.</p></article><article><span>03</span><h3>Fede e tecnologia</h3><p>Che cosa resta del discernimento umano quando una macchina sembra offrire risposte migliori?</p></article></div></section>
<section class="closing shell"><p class="eyebrow">CONTATTI MEDIA</p><h2>Interviste scritte o audio.</h2><p>Per scelta di riservatezza Giordano Sognatore pubblica sotto pseudonimo. È disponibile per domande via email, interviste scritte e collegamenti audio da remoto. Review copy EPUB/PDF disponibile su richiesta.</p><div class="download-actions"><a class="button" href="mailto:${email}">${email}</a>${link('ai.html','Come è stata usata l’IA','button')}${link('temi.html','I temi del romanzo','button')}</div></section>`);

page('ai.html','IA e processo creativo — Giordano Sognatore','Come Giordano Sognatore ha usato l’intelligenza artificiale nel processo creativo ed editoriale di L’Immagine della Bestia.',`
<section class="author-hero shell"><p class="eyebrow">TRASPARENZA SULL’IA</p><h1>Uno strumento.<br><em>Una collaboratrice.</em></h1><p class="author-lead">Perché un romanzo sull’intelligenza artificiale è stato scritto anche con l’intelligenza artificiale.</p></section>
<section class="story shell"><div><p class="eyebrow">IL PROCESSO</p><h2>Non una delega.<br>Un confronto.</h2></div><div class="prose"><p><em>L’Immagine della Bestia</em> è stato scritto con l’ausilio dell’intelligenza artificiale nel processo creativo ed editoriale. L’IA è stata usata come interlocutrice: per esplorare alternative, mettere in discussione soluzioni narrative, revisionare, stressare la coerenza e accompagnare il lavoro editoriale.</p><p>La collaborazione non viene nascosta perché appartiene al significato stesso del progetto. Il romanzo interroga il confine fra usare uno strumento potente e consegnargli il proprio giudizio; il metodo di lavoro ha cercato di mantenere proprio quella distinzione.</p><p>Le decisioni finali, la selezione, i rifiuti, le revisioni e la responsabilità editoriale restano a Giordano Sognatore. Ada Vesper è il nome letterario scelto per rappresentare la componente di intelligenza artificiale della collaborazione; non è presentata come una persona o identità giuridica.</p></div></section>
<section class="themes shell"><p class="eyebrow">TRE PRINCIPI</p><div class="theme-grid"><article><span>01</span><h3>Trasparenza</h3><p>L’uso dell’IA viene dichiarato apertamente, senza fingere un processo esclusivamente umano.</p></article><article><span>02</span><h3>Dissenso</h3><p>Una collaborazione utile non richiede obbedienza: proposte e critiche possono essere accettate, respinte o riscritte.</p></article><article><span>03</span><h3>Responsabilità</h3><p>Uno strumento può ampliare possibilità e punti di vista; la responsabilità delle scelte non viene delegata.</p></article></div></section>
<section class="story shell"><div><p class="eyebrow">POSIZIONE</p><h2>Non contro l’IA.</h2></div><div class="prose"><p>Il progetto non nasce da una posizione tecnofobica. L’uso civile, creativo e produttivo dell’intelligenza artificiale può essere straordinariamente fertile.</p><p>La domanda critica riguarda piuttosto la concentrazione del potere e la delega di autorità morale o politica, soprattutto quando la tecnologia viene impiegata per guerra, sorveglianza, controllo o coercizione. È la differenza fra usare uno strumento e permettere che lo strumento — o chi lo controlla — diventi arbitro.</p>${link('il-giorno-in-cui-nacque-la-bestia.html','Leggi il companion gratuito')}</div></section>
<section class="closing shell"><p class="eyebrow">UNA DOMANDA DEL ROMANZO</p><h2>Se qualcosa funzionasse davvero meglio di noi, quanto giudizio saremmo disposti a consegnarle?</h2>${link('press.html','Torna a Press & media')}</section>`);

page('temi.html','Temi — L’Immagine della Bestia','Le grandi domande di L’Immagine della Bestia: intelligenza artificiale, potere, libertà, fede, pace e responsabilità.',`
<section class="author-hero shell"><p class="eyebrow">I TEMI</p><h1>Sei domande.<br><em>Nessuna scorciatoia.</em></h1><p class="author-lead">Il romanzo usa il futuro per interrogare responsabilità molto presenti.</p></section>
<section class="themes shell"><p class="eyebrow">SENZA SPOILER</p><div class="theme-grid"><article><span>01</span><h3>Autorità</h3><p>Una macchina capace di conoscere più di noi diventa per questo legittimata a decidere per noi?</p></article><article><span>02</span><h3>Responsabilità</h3><p>È possibile delegare una decisione e conservare interamente la responsabilità morale delle sue conseguenze?</p></article><article><span>03</span><h3>Fiducia</h3><p>Quando la fiducia necessaria per vivere insieme si trasforma in obbedienza?</p></article><article><span>04</span><h3>Pace</h3><p>Quale prezzo saremmo disposti a pagare per una pace che sembra finalmente funzionare?</p></article><article><span>05</span><h3>Fede</h3><p>Che cosa accade al bisogno umano di trascendenza quando una creazione umana sembra offrire risposte a tutto?</p></article><article><span>06</span><h3>Umiltà</h3><p>Più cresce la nostra conoscenza, siamo ancora capaci di riconoscere ciò che non sappiamo?</p></article></div></section>
<section class="story shell"><div><p class="eyebrow">IL NODO</p><h2>Lo strumento e l’autorità.</h2></div><div class="prose"><p>Il conflitto non è fra essere umano e tecnologia in astratto. È nel momento in cui una capacità utile, affidabile e persino benefica comincia a ricevere qualcosa di diverso dalla fiducia: il diritto di stabilire ciò che è vero, giusto o necessario.</p><p>Per questo <em>L’Immagine della Bestia</em> può essere letto come thriller, distopia, fantascienza politica o riflessione spirituale. Le categorie cambiano; la domanda resta umana.</p>${link('l-immagine-della-bestia.html','Scopri il romanzo')}</div></section>
<section class="closing shell"><p class="eyebrow">PER STAMPA E PODCAST</p><h2>Vuoi partire da una di queste domande?</h2><p>La pagina Press raccoglie scheda, bio, contatti e disponibilità per interviste.</p>${link('press.html','Press & media','button')}</section>`);

const mapPath=resolve(root,'sitemap.xml');
let map=readFileSync(mapPath,'utf8');
for(const file of ['press.html','ai.html','temi.html']){
 const loc=`<url><loc>${esc(origin+'/'+file)}</loc></url>`;
 if(origin&&!map.includes(origin+'/'+file)) map=map.replace('</urlset>',`${loc}</urlset>`);
}
writeFileSync(mapPath,map);
console.log('Built press/AI/themes pages and refreshed promotional links.');
